// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.EntityFramework;

#nullable disable

namespace CodeRag.Shared.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20250610072029_ReintroduceProjectIdInVector")]
    partial class ReintroduceProjectIdInVector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.EntityFramework.DbModels.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CSharpXmlSummaryInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChatMaxNumberOfAnswersBackFromDocumentationSearch")
                        .HasColumnType("int");

                    b.Property<int>("ChatMaxNumberOfAnswersBackFromSourceCodeSearch")
                        .HasColumnType("int");

                    b.Property<double>("ChatScoreShouldBeLowerThanThisInDocumentSearch")
                        .HasColumnType("float");

                    b.Property<double>("ChatScoreShouldBeLowerThanThisInSourceCodeSearch")
                        .HasColumnType("float");

                    b.Property<bool>("ChatUseDocumentationSearch")
                        .HasColumnType("bit");

                    b.Property<bool>("ChatUseSourceCodeSearch")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("GitHubOwner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GitHubRepo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrReviewMaxNumberOfAnswersBackFromDocumentationSearch")
                        .HasColumnType("int");

                    b.Property<int>("PrReviewMaxNumberOfAnswersBackFromSourceCodeSearch")
                        .HasColumnType("int");

                    b.Property<double>("PrReviewScoreShouldBeLowerThanThisInDocumentSearch")
                        .HasColumnType("float");

                    b.Property<double>("PrReviewScoreShouldBeLowerThanThisInSourceCodeSearch")
                        .HasColumnType("float");

                    b.Property<bool>("PrReviewUseDocumentationSearch")
                        .HasColumnType("bit");

                    b.Property<bool>("PrReviewUseSourceCodeSearch")
                        .HasColumnType("bit");

                    b.Property<string>("PullRequestReviewInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XmlSummariesMaxNumberOfAnswersBackFromDocumentationSearch")
                        .HasColumnType("int");

                    b.Property<int>("XmlSummariesMaxNumberOfAnswersBackFromSourceCodeSearch")
                        .HasColumnType("int");

                    b.Property<double>("XmlSummariesScoreShouldBeLowerThanThisInDocumentSearch")
                        .HasColumnType("float");

                    b.Property<double>("XmlSummariesScoreShouldBeLowerThanThisInSourceCodeSearch")
                        .HasColumnType("float");

                    b.Property<bool>("XmlSummariesUseDocumentationSearch")
                        .HasColumnType("bit");

                    b.Property<bool>("XmlSummariesUseSourceCodeSearch")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Shared.EntityFramework.DbModels.ProjectSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileIgnorePatterns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("GitGubLastCommitTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GitHubOwner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GitHubRepo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IgnoreFileIfMoreThanThisNumberOfLines")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("MarkdownChunkIgnoreIfLessThanThisAmountOfChars")
                        .HasColumnType("int");

                    b.Property<string>("MarkdownChunkLineIgnorePatterns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MarkdownFilenameEqualDocUrlSubpage")
                        .HasColumnType("bit");

                    b.Property<bool>("MarkdownIgnoreCommentedOutContent")
                        .HasColumnType("bit");

                    b.Property<bool>("MarkdownIgnoreImages")
                        .HasColumnType("bit");

                    b.Property<bool>("MarkdownIgnoreMicrosoftLearnNoneCsharpContent")
                        .HasColumnType("bit");

                    b.Property<int>("MarkdownLevelsToChunk")
                        .HasColumnType("int");

                    b.Property<int>("MarkdownOnlyChunkIfMoreThanThisNumberOfLines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProjectEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Recursive")
                        .HasColumnType("bit");

                    b.Property<string>("RootUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEntityId");

                    b.ToTable("ProjectSources");
                });

            modelBuilder.Entity("Shared.EntityFramework.DbModels.VectorEntity", b =>
                {
                    b.Property<Guid>("VectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Id")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Kind")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Parent")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ParentKind")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfIngestion")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Vector")
                        .HasColumnType("vector(1536)");

                    b.HasKey("VectorId");

                    b.HasIndex("DataType");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SourceId");

                    b.ToTable("vector_sources");
                });

            modelBuilder.Entity("Shared.EntityFramework.DbModels.ProjectSourceEntity", b =>
                {
                    b.HasOne("Shared.EntityFramework.DbModels.ProjectEntity", "Project")
                        .WithMany("Sources")
                        .HasForeignKey("ProjectEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Shared.EntityFramework.DbModels.ProjectEntity", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
